/**
 * Receipt Wrangler API.
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface QuickScanCommand { 
    file: Blob;
    /**
     * Group foreign key
     */
    groupId: number;
    /**
     * User foreign key
     */
    paidByUserId: number;
    /**
     * Status of quick scanned receipt
     */
    status: QuickScanCommand.StatusEnum;
}
export namespace QuickScanCommand {
    export type StatusEnum = 'OPEN' | 'NEEDS_ATTENTION' | 'RESOLVED' | 'DRAFT';
    export const StatusEnum = {
        OPEN: 'OPEN' as StatusEnum,
        NEEDSATTENTION: 'NEEDS_ATTENTION' as StatusEnum,
        RESOLVED: 'RESOLVED' as StatusEnum,
        DRAFT: 'DRAFT' as StatusEnum
    };
}